"""Add user_id to doctors

Revision ID: e2ac65766f4d
Revises: 65fb5e1a4e70
Create Date: 2026-08-24 11:31:04.521510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ac65766f4d'
down_revision: Union[str, Sequence[str], None] = '65fb5e1a4e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'doctors', ['user_id'])
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_column('doctors', 'user_id')
    # ### end Alembic commands ###
